info:
  contact: {}
paths:
  /dbalbums:
    get:
      description: Retrieves a list of all albums
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Albums
      tags:
      - albums
swagger: "2.0"
